"""
    Check that diff two files works.

    The test provides two text strings:
    1) The first task creates a file from each string
    2) The second task diffs the two files
    3) The result is the number of lines generated by the diff
"""

def test_case_unequal(workflow_runner):
    inputs = {
        "aStr" : "hello world",
        "bStr" : "Nothing much"
    }
    outputs = {
        "result" : 4
    }
    workflow_runner("main.wdl", inputs, outputs)

def test_case_equal(workflow_runner):
    inputs = {
        "aStr" : "hello world",
        "bStr" : "hello world",
    }
    outputs = {
        "result" : 0
    }
    workflow_runner("main.wdl", inputs, outputs)
